const projectsZh={
rag:{title:'企業 RAG 與模型評估',sub:'技術實務方向 / RAG · GPU inference · Evaluation',intro:'我關注企業知識應用中的三個問題：找得到資料嗎？回答有依據嗎？系統能在資源限制下運作嗎？',sections:[['評估方法','將 embedding、reranking、脈絡組裝與生成分開檢視，以受控比較觀察單一元件改變如何影響完整流程。元件加速不直接等同於使用者感受到的端到端加速。'],['工程考量','關注 Docker 部署、模型與向量資料庫整合、VRAM 用量及併發延遲。除了錯誤率，也觀察服務是否在高負載下變慢。'],['品質判讀','同時查看檢索相關性、引用依據、回答一致性與拒答行為，保留未改善與不適合採用的結果。']],limit:'此頁呈現方法與關注範圍。公司內部數據、客戶資料與實作細節不在公開作品中展示。'},
agent:{title:'多代理客服流程原型',sub:'個人 PoC / LangGraph · Gemini · Streamlit',intro:'將使用者問題分流給不同角色，讓模型透過工具取得資訊，並在介面上呈現路由過程。',sections:[['實作內容','以 StateGraph 建立 Router、Tech、Sales、General 節點；技術與業務角色各自綁定工具，透過 ToolNode 執行後回到 Agent 組織回答。'],['值得說明的取捨','Router 的派單訊息顯示在介面中，但傳給下一個 Agent 前移除，避免展示用文字干擾對話脈絡。帳務問題與銷售推薦也需要不同工具與任務邊界。'],['下一步驗證','建立固定意圖測試集，分別評估路由正確性、工具參數、回應品質與失敗情境，再考慮接入真實服務。']],limit:'工具目前回傳模擬資料，屬概念驗證；不代表已接入電信公司或正式工單系統。此實作使用 Function Calling，未以此宣稱已建置 MCP 服務。'},
n8n:{title:'n8n 多代理股市分析',sub:'培訓專題 / n8n · JavaScript · TWSE API · RAG',intro:'將個股、大盤與新聞資料整理成可供模型使用的脈絡，探索工作流程自動化與有來源的回答。',sections:[['資料流程','拆分主流程、大盤資料、個股資料與新聞知識庫。個股流程組合十二個月份的 API 請求，處理日期與數值格式，再計算 MA5、MA10、MA20、MA60、MA120。'],['模型與檢索','以規則辨識股票代碼與部分意圖，再將整理後的資料交給 Agent。新聞透過 RSS、embedding 與向量檢索，作為回答的補充依據。'],['工程觀察','不同 API 回傳結構需要先標準化。流程拆分能方便追查資料在哪個步驟遺失，也能區分資料處理錯誤與模型回答問題。']],limit:'這是分析流程原型，不是經驗證的股價預測或交易績效。向量儲存與外部來源的穩定性仍影響結果；不宣稱 RAG 能消除幻覺。',image:'assets/n8n-workflow.png',alt:'n8n 股市分析主流程截圖'},
pcb:{title:'PCB 瑕疵影像分類',sub:'學習專案 / PyTorch · ResNet · 圖像分類',intro:'使用預訓練 ResNet 進行六類 PCB 瑕疵影像分類，從模型訓練到混淆矩陣，理解錯誤集中在哪些類別。',sections:[['實作內容','保留 ResNet18 與 ResNet50 的實驗程式，使用影像翻轉、旋轉與裁切等資料增強，並嘗試凍結層、類別加權損失與學習率調整。'],['結果口徑','既有混淆矩陣顯示：原始六分類 89.36%；依類別對應合併為三類後為 94.33%。合併改變了問題定義，兩者不能視為同一指標的模型進步。'],['驗證限制','既有評估程式讀取驗證集，訓練也以驗證結果選擇模型。這些數字作為歷史驗證結果呈現，獨立測試集與切分重現仍待補足。']],limit:'本專案是影像分類原型，未宣稱完成產線部署、物件定位或分割，也不將合併三類結果寫成六類 95%。',image:'assets/pcb-results.png',alt:'六類與三類的歷史驗證混淆矩陣'},
quant:{title:'訂單流資料與研究系統',sub:'個人研究 / Python · FastAPI · WebSocket · SQLite',intro:'把逐筆行情、指標計算、即時圖表與歷史重放接在一起，讓研究過程可以回溯。',sections:[['系統流程','逐筆行情落地後進行 K 棒聚合與訂單流計算，以 FastAPI 和 WebSocket 推送到前端儀表板，呈現 Footprint、Delta、CVD 與 VWAP 等資訊。'],['設計重點','以唯一鍵去重、資料備份與歷史重放支援研究。讓歷史資料重放至共用引擎，減少即時與回測兩套邏輯的差異。'],['研究紀律','事先定義假設與判定條件，記錄成本、失敗與結論變更。工程能力與策略獲利是不同問題，公開作品以資料管線、系統架構與驗證方法為主。']],limit:'此處展示個人研究系統，不代表策略具備穩定獲利能力。',image:'assets/orderflow-dashboard.png',alt:'訂單流研究系統公開展示版儀表板'},
code:{title:'CodeExplain 程式碼閱讀工具',sub:'個人原型 / Gemini API · Streamlit · Graphviz',intro:'以四個模式協助閱讀陌生程式：白話解釋、流程導覽、README 生成與重構建議。',sections:[['實作內容','透過 Gemini 產生文字或結構化 JSON，再以 Graphviz 繪製流程，讓使用者切換步驟查看對應程式片段。'],['介面狀態','以 Streamlit session_state 保留回應與模式，避免操作選單後遺失結果；另處理 JSON 解析失敗情況。']],limit:'模型輸出的解釋與重構內容仍需人工審查，未宣稱已量測開發效率提升。'},
battery:{title:'電池 SOH／SOC 估測',sub:'大學專題 / 電機工程 · 感測資料 · Arduino',intro:'從鋰電池的電壓與電流量測出發，探索電量與健康狀態的估測。',sections:[['專題方向','以一階 RC 等效電路描述電池特性，透過充放電量測取得參數，再結合卡爾曼濾波的狀態估測方法。'],['系統整合','專題報告包含感測器輸入、Arduino 運算與 LCD 顯示流程。這段經驗是我將實體訊號、資料處理與軟體串連的起點。']],limit:'此頁依既有專題報告描述，不另外宣稱未核實的估測誤差或實際應用成效。'}
};
const isEnglish=document.documentElement.lang==='en';
const projects=isEnglish?window.projectsEn:projectsZh;
const dialog=document.querySelector('#project-dialog');
function element(tag,text,className){const el=document.createElement(tag);if(text)el.textContent=text;if(className)el.className=className;return el;}
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const p=projects[button.dataset.project];if(!p)return;const content=document.querySelector('#dialog-content');content.replaceChildren();content.append(element('p',p.sub,'dialog-sub'));const title=element('h2',p.title);title.id='dialog-title';content.append(title,element('p',p.intro));for(const [heading,body] of p.sections)content.append(element('h3',heading),element('p',body));if(p.image){const img=element('img');img.src=p.image;img.alt=p.alt;content.append(img);}content.append(element('p',p.limit,'caveat'));dialog.showModal();dialog.scrollTop=0;document.body.classList.add('no-scroll');}));
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('close',()=>document.body.classList.remove('no-scroll'));
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#nav');
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?(isEnglish?'Close navigation':'關閉導覽選單'):(isEnglish?'Open navigation':'開啟導覽選單'));nav.classList.toggle('is-open',open);});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label',isEnglish?'Open navigation':'開啟導覽選單');}));
document.querySelector('#copy-email').addEventListener('click',async()=>{const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText('ken7040532@gmail.com');status.textContent=isEnglish?'Email copied':'Email 已複製';}catch{status.textContent=isEnglish?'Select the email address to copy it, or click it to open your mail app.':'請選取上方 Email 複製，或點擊開啟郵件。'}});
