name: Build and Deploy
env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  USE_GITHUB_DATA: "true"
  MEDIUM_USERNAME: "saadpasta" 
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * 1" 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3 
        with:
          persist-credentials: false

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 16  # 💡 經過確認，這個模板在 Node 16 下運行最穩定，我們退回一點點確保相容性

      - name: Install and Build 🔧
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: build
